// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Representant_Deposit_Slice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Representant_Deposit_Slice));
        
        string IMigrationMetadata.Id
        {
            get { return "201512071517064_Representant_Deposit_Slice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
