// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modif_RptPaymentDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modif_RptPaymentDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201609081647211_modif_RptPaymentDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
