// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NumeroFacture_CustOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NumeroFacture_CustOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201609191258163_NumeroFacture_CustOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
