// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Prescription_Remove_For_CustomerOrderLine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Prescription_Remove_For_CustomerOrderLine));
        
        string IMigrationMetadata.Id
        {
            get { return "201609161149269_Prescription_Remove_For_CustomerOrderLine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
