// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sale_PoliceAssurance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sale_PoliceAssurance));
        
        string IMigrationMetadata.Id
        {
            get { return "201609071609258_Sale_PoliceAssurance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
