// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Table_ProductDamageLine_ProductDamageReason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_ProductDamageLine_ProductDamageReason));
        
        string IMigrationMetadata.Id
        {
            get { return "201604150649204_Table_ProductDamageLine_ProductDamageReason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
