// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_customer_order_add_assure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_customer_order_add_assure));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061530016_remove_customer_order_add_assure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
