// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductQty_dbl_inventory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductQty_dbl_inventory));
        
        string IMigrationMetadata.Id
        {
            get { return "201606040858235_ProductQty_dbl_inventory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
