// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Database_remove_Special_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_remove_Special_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "201608300617172_Database_remove_Special_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
