// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class index_diametre_specialOrder_cat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(index_diametre_specialOrder_cat));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221217330_index_diametre_specialOrder_cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
