// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class field_Codeclient_required_specialOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(field_Codeclient_required_specialOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201606120602533_field_Codeclient_required_specialOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
