// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sale_addfield_CustomerOrderID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sale_addfield_CustomerOrderID));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070949016_sale_addfield_CustomerOrderID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
