// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modif_Sale_SaleDateHours : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modif_Sale_SaleDateHours));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181600165_Modif_Sale_SaleDateHours"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
