// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_field_Post_Receive_SOByID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field_Post_Receive_SOByID));
        
        string IMigrationMetadata.Id
        {
            get { return "201808300549464_add_field_Post_Receive_SOByID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
