// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modif_table_cumulsaleandbill_PurchasePrice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modif_table_cumulsaleandbill_PurchasePrice));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211059556_modif_table_cumulsaleandbill_PurchasePrice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
