// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_table_AccountingTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_table_AccountingTask));
        
        string IMigrationMetadata.Id
        {
            get { return "201811101958390_Update_table_AccountingTask"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
