// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sale_RendezVous_SO_Variable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sale_RendezVous_SO_Variable));
        
        string IMigrationMetadata.Id
        {
            get { return "201808280616005_Sale_RendezVous_SO_Variable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
