// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_modif_customernum_with_Prescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_modif_customernum_with_Prescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201908050524387_New_modif_customernum_with_Prescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
