// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_BorderoDepot_Entity_Heure_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_BorderoDepot_Entity_Heure_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201908250445102_update_BorderoDepot_Entity_Heure_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
