// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_isAuthoriseSale_consultdilation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_isAuthoriseSale_consultdilation));
        
        string IMigrationMetadata.Id
        {
            get { return "201910290559250_add_isAuthoriseSale_consultdilation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
