// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Consultations_RaisonRdv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Consultations_RaisonRdv));
        
        string IMigrationMetadata.Id
        {
            get { return "202004071223140_Consultations_RaisonRdv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
