// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class manage_acuite_visuel_left_and_right_in_ConsultOldPrescr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manage_acuite_visuel_left_and_right_in_ConsultOldPrescr));
        
        string IMigrationMetadata.Id
        {
            get { return "202005061857206_manage_acuite_visuel_left_and_right_in_ConsultOldPrescr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
