// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CumulSaleAndBill_IsReceived_IsMounted_DeliverID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CumulSaleAndBill_IsReceived_IsMounted_DeliverID));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051312171_CumulSaleAndBill_IsReceived_IsMounted_DeliverID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
