// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_seller_on_sale_and_insured : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_seller_on_sale_and_insured));
        
        string IMigrationMetadata.Id
        {
            get { return "202004252147509_add_seller_on_sale_and_insured"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
