// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Manage_Lens_Mounting_Damage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manage_Lens_Mounting_Damage));
        
        string IMigrationMetadata.Id
        {
            get { return "202012060801154_Manage_Lens_Mounting_Damage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
