// <auto-generated />
namespace FatSod.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_colum_remise_to_Ensurance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_colum_remise_to_Ensurance));
        
        string IMigrationMetadata.Id
        {
            get { return "202305301231485_add_colum_remise_to_Ensurance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
